# Welcome to Jekyll!
#
# Toto je soubor s hlavním nastavením. Na začátku je nastavení proměných, které
# je třeba přispůsobit si pro váš web. Později v anglicky popsané části jsou více
# technické nastavení
#

title: Pirátská strana Praha
email: to@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
# dobré keywords jsou ty co lidé piší do googlu když hledají naši stránku
keywords: pražský, kraj, praha, piráti, česká pirátská strana, svoboda, demokracie 
url: "https://praha.pirati.cz" # the base hostname & protocol for your site

mediaStorage: praha

administrator:
  email: jitka.novotna@pirati.cz, jan.louzek@pirati.cz

organization:
  name: Pirátská strana Praha
  shortName: Piráti Praha
  email: kodo-praha@pirati.cz
  phone: +420 606 168 306
  address: |
    Na Moráni 3,
    120 00 Praha 2
  #residenceImg: kontakt/novepice.jpg
  mapLink: https://mapy.cz/zakladni?x=14.4151543&y=50.0733415&z=18&source=addr&id=9018965&q=Na%20Mor%C3%A1ni%203
  redmineLink: https://redmine.pirati.cz/projects
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010

# Nastavení zobrazení tabulky kontaktů.
# Lze využít:
# 1) předdefinované typy (organizationEmail, organizationRedmineLink, organizationPhone, organizationTransparentAccount, organizationDataBox, piratiRootWebsite)
# 2) vlastní řádky - zde je nutné jako type dát `custom` a vyplnit `label` a `body`
contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationPhone
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
  - type: piratiRootWebsite

calendar:
  # For nice look of the calendar, make sure you get Google Calendar API key
  # and start the app with the env var `GOOGLE_CALENDAR_APIKEY=[myapikey] bundle exec jekyll serve`.
  # For deployment, contact website administrator to set you env variable.
  title: Celopražský kalendář
  apiKey: AIzaSyBdjZxz4r9lPyD3CiSxQa6G3mf47ezI7Ks
  id: rm0h4oqjk2j2o0615sc4d1slfk@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&showNav=0&showDate=0&showPrint=0&showTabs=0&showCalendars=0&showTz=0&mode=AGENDA&height=500&wkst=2&hl=cs&bgcolor=%23FFFFFF&src=kddvdvu3adcjef2kro4j6mm838%40group.calendar.google.com&color=%232952A3&ctz=Europe%2FPrague

facebook:
  loadSDK: true
  #vyplně adresu vaší stranky, funguje pouze na stránky nikoliv skupiny
  profilePage: https://www.facebook.com/CeskaPiratskaStranaPraha/
  profilePageName: Piráti - Praha
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: PiratskaStrana

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/viewforum.php?f=78&sid=44b065968620303e7f4058202f146b94

github:
  url: https://github.com/pirati-web/praha.pirati.cz/
  branch: master

#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

github_username:  pirati-web

sass:
  style: compressed
  sass_dir: _sass

theme: jekyll-theme-pirati

markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-environment-variables
paginate_path: "/aktuality/:num/"
paginate: 12

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /tiskove-zpravy/:title/
collections:
  people:
    output: true
    permalink: /lide/:path/

  program:
    output: true
    permalink: /komunalni-volby/program/:path/

  volby2018:
    output: true
    permalink: /volby-2018/:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - profile
        - people
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
         - garant
         - program
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      rbar:
        - foto
        - personContact
        - people
emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-7.7.1/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img/posts
    - assets/snippet
    - assets/img    
    - _sass

styleguide_base_url: 'https://styleguide.pir-test.eu/latest/'
